import {initialState as offers} from "../../store/reducers/offers/offers";
import {initialState as room} from "../../store/reducers/room/room";
import {initialState as favorites} from "../../store/reducers/favorites/favorites";
import {initialState as authorizationStatus} from "../../store/reducers/authorization-status/authorization-status";
import {initialState as sortOrder} from "../../store/reducers/sort-order/sort-order";
import {initialState as currentCityName} from "../../store/reducers/current-city-name/current-city-name";
import {initialState as currentUser} from "../../store/reducers/current-user/current-user";
import {initialState as serverAvailability} from "../../store/reducers/server-availability/server-availability";

export const initial = {
  offers,
  room,
  favorites,
  authorizationStatus,
  sortOrder,
  currentCityName,
  currentUser,
  serverAvailability,
};

export const filled = {
  authorizationStatus: `AUTH`,
  sortOrder: `Popular`,
  currentCityName: `Paris`,
  serverAvailability: true,
  currentUser: {
    id: 1,
    email: `123@mail.ru`,
    name: `123`,
    avatarUrl: `https://assets.htmlacademy.ru/intensives/javascript-3/avatar/7.jpg`,
    isPro: false,
  },
  offers: {
    isLoaded: true,
    entities: [
      {
        city: {
          name: `Paris`,
          location: {
            latitude: 48.85661,
            longitude: 2.351499,
            zoom: 13,
          },
        },
        previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
        images: [
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
        ],
        title: `Canal View Prinsengracht`,
        isFavorite: false,
        isPremium: true,
        rating: 3.5,
        type: `apartment`,
        bedrooms: 2,
        maxAdults: 7,
        price: 340,
        goods: [
          `Baby seat`,
          `Towels`,
          `Dishwasher`,
          `Coffee machine`,
          `Air conditioning`,
          `Washer`,
          `Fridge`,
          `Breakfast`,
          `Laptop friendly workspace`,
        ],
        host: {
          id: 25,
          name: `Angelina`,
          isPro: true,
          avatarUrl: `img/avatar-angelina.jpg`,
        },
        description: `Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.`,
        location: {
          latitude: 48.84461,
          longitude: 2.374499,
          zoom: 16,
        },
        id: 1,
      },
      {
        city: {
          name: `Cologne`,
          location: {
            latitude: 50.938361,
            longitude: 6.959974,
            zoom: 13,
          },
        },
        previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
        images: [
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
        ],
        title: `Nice, cozy, warm big bed apartment`,
        isFavorite: true,
        isPremium: false,
        rating: 2.1,
        type: `room`,
        bedrooms: 1,
        maxAdults: 3,
        price: 196,
        goods: [
          `Laptop friendly workspace`,
          `Fridge`,
          `Breakfast`,
          `Baby seat`,
          `Washer`,
          `Air conditioning`,
          `Towels`,
        ],
        host: {
          id: 25,
          name: `Angelina`,
          isPro: true,
          avatarUrl: `img/avatar-angelina.jpg`,
        },
        description: `Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.`,
        location: {
          latitude: 50.934361,
          longitude: 6.943974,
          zoom: 16,
        },
        id: 2,
      },
      {
        city: {
          name: `Amsterdam`,
          location: {
            latitude: 52.37454,
            longitude: 4.897976,
            zoom: 13,
          },
        },
        previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
        images: [
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
        ],
        title: `Amazing and Extremely Central Flat`,
        isFavorite: false,
        isPremium: false,
        rating: 2.3,
        type: `room`,
        bedrooms: 1,
        maxAdults: 1,
        price: 145,
        goods: [`Laptop friendly workspace`, `Breakfast`],
        host: {
          id: 25,
          name: `Angelina`,
          isPro: true,
          avatarUrl: `img/avatar-angelina.jpg`,
        },
        description: `A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.`,
        location: {
          latitude: 52.36854,
          longitude: 4.887976,
          zoom: 16,
        },
        id: 3,
      },
      {
        city: {
          name: `Brussels`,
          location: {
            latitude: 50.846557,
            longitude: 4.351697,
            zoom: 13,
          },
        },
        previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
        images: [
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
        ],
        title: `Loft Studio in the Central Area`,
        isFavorite: false,
        isPremium: false,
        rating: 3.8,
        type: `apartment`,
        bedrooms: 1,
        maxAdults: 7,
        price: 209,
        goods: [
          `Breakfast`,
          `Air conditioning`,
          `Laptop friendly workspace`,
          `Washer`,
          `Baby seat`,
          `Fridge`,
          `Towels`,
        ],
        host: {
          id: 25,
          name: `Angelina`,
          isPro: true,
          avatarUrl: `img/avatar-angelina.jpg`,
        },
        description: `A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.`,
        location: {
          latitude: 50.837557,
          longitude: 4.339697,
          zoom: 16,
        },
        id: 4,
      },
      {
        city: {
          name: `Paris`,
          location: {latitude: 48.85661, longitude: 2.351499, zoom: 13},
        },
        previewImage:
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
        images: [
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
        ],
        title: `The Joshua Tree House`,
        isFavorite: true,
        isPremium: false,
        rating: 2.1,
        type: `hotel`,
        bedrooms: 4,
        maxAdults: 9,
        price: 346,
        goods: [
          `Dishwasher`,
          `Towels`,
          `Fridge`,
          `Air conditioning`,
          `Baby seat`,
          `Washer`,
          `Laptop friendly workspace`,
          `Breakfast`,
        ],
        host: {
          id: 25,
          name: `Angelina`,
          isPro: true,
          avatarUrl: `img/avatar-angelina.jpg`,
        },
        description:
          `I rent out a very sunny and bright apartment only 7 minutes walking distance to the metro station. The apartment has a spacious living room with a kitchen, one bedroom and a bathroom with mit bath. A terrace can be used in summer.`,
        location: {latitude: 48.834610000000005, longitude: 2.364499, zoom: 16},
        id: 13,
      },
      {
        city: {
          name: `Paris`,
          location: {latitude: 48.85661, longitude: 2.351499, zoom: 13},
        },
        previewImage:
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
        images: [
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
        ],
        title: `Loft Studio in the Central Area`,
        isFavorite: false,
        isPremium: true,
        rating: 3.4,
        type: `house`,
        bedrooms: 4,
        maxAdults: 7,
        price: 558,
        goods: [
          `Air conditioning`,
          `Breakfast`,
          `Laptop friendly workspace`,
          `Washer`,
          `Baby seat`,
        ],
        host: {
          id: 25,
          name: `Angelina`,
          isPro: true,
          avatarUrl: `img/avatar-angelina.jpg`,
        },
        description:
          `A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.`,
        location: {latitude: 48.846610000000005, longitude: 2.374499, zoom: 16},
        id: 23,
      },
      {
        city: {
          name: `Paris`,
          location: {latitude: 48.85661, longitude: 2.351499, zoom: 13},
        },
        previewImage:
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
        images: [
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
          `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
        ],
        title: `Penthouse, 4-5 rooms + 5 balconies`,
        isFavorite: true,
        isPremium: false,
        rating: 2.6,
        type: `room`,
        bedrooms: 1,
        maxAdults: 2,
        price: 259,
        goods: [
          `Air conditioning`,
          `Breakfast`,
          `Washer`,
          `Laptop friendly workspace`,
        ],
        host: {
          id: 25,
          name: `Angelina`,
          isPro: true,
          avatarUrl: `img/avatar-angelina.jpg`,
        },
        description:
          `I rent out a very sunny and bright apartment only 7 minutes walking distance to the metro station. The apartment has a spacious living room with a kitchen, one bedroom and a bathroom with mit bath. A terrace can be used in summer.`,
        location: {latitude: 48.837610000000005, longitude: 2.364499, zoom: 16},
        id: 76,
      },
    ],
  },
  room: {
    isRoomLoaded: true,
    isNearbyLoaded: true,
    nearIds: [13, 23, 76],
  },
  favorites: {
    isLoaded: true,
    ids: [2, 13, 76],
  },
};

